//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mqtt_Terminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mqtt_Terminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-connect when opened.
        /// </summary>
        public static string AutoConnect {
            get {
                return ResourceManager.GetString("AutoConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-open at start-up.
        /// </summary>
        public static string AutoOpen {
            get {
                return ResourceManager.GetString("AutoOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-subscribe when opened.
        /// </summary>
        public static string AutoSub {
            get {
                return ResourceManager.GetString("AutoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean session.
        /// </summary>
        public static string CleanSession {
            get {
                return ResourceManager.GetString("CleanSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload layout.
        /// </summary>
        public static string LayoutReload {
            get {
                return ResourceManager.GetString("LayoutReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save layout.
        /// </summary>
        public static string LayoutSave {
            get {
                return ResourceManager.GetString("LayoutSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max messages stored.
        /// </summary>
        public static string MaxMessages {
            get {
                return ResourceManager.GetString("MaxMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnection interval [s].
        /// </summary>
        public static string ReconnectionInterval {
            get {
                return ResourceManager.GetString("ReconnectionInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect on failure.
        /// </summary>
        public static string ReconnectOnFailure {
            get {
                return ResourceManager.GetString("ReconnectOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resubscribe on failure.
        /// </summary>
        public static string ResubscribeOnFailure {
            get {
                return ResourceManager.GetString("ResubscribeOnFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration.
        /// </summary>
        public static string SaveConfiguration {
            get {
                return ResourceManager.GetString("SaveConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URI.
        /// </summary>
        public static string ServerUri {
            get {
                return ResourceManager.GetString("ServerUri", resourceCulture);
            }
        }
    }
}
